I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 36, in script call
    call credits
  File "game/script.rpy", line 48, in script
    with pause(3)
  File "game/script.rpy", line 48, in <module>
    with pause(3)
NameError: name 'pause' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 36, in script call
    call credits
  File "game/script.rpy", line 48, in script
    with pause(3)
  File "C:\Users\Tyler\Downloads\renpy-6.99.12.4-sdk\renpy\ast.py", line 1268, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Tyler\Downloads\renpy-6.99.12.4-sdk\renpy\python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Tyler\Downloads\renpy-6.99.12.4-sdk\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 48, in <module>
    with pause(3)
NameError: name 'pause' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Video Game Development LOVE!! Testing V0.0 1.0
